name: CI # Darle nombre


on: # Indicamos el trigger
  push: # La accion que desencadena el triger
    branches:
      - main
    
jobs: # puede tener 1 o más jobs
  test:
    run-on: ubuntu-latest #la maquina donde se hará la prueba

    steps:
      - name: Checkout_code
        uses: actions/checkout@v3 # descargar el repositorio
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
        python-version: '3.8'
        
      - name: Run test
        run: |
        python -m unittest test/test-main.py